services:
  postgres:
    image: postgres:18
    container_name: soloservis_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soloservis

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      - ../../backend/db/migrations:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_data:
