// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	LogoUrl    pgtype.Text `json:"logo_url"`
	WebsiteUrl pgtype.Text `json:"website_url"`
	Active     bool        `json:"active"`
}

type Product struct {
	ID          int64       `json:"id"`
	PublicID    pgtype.UUID `json:"public_id"`
	CategoryID  pgtype.Int8 `json:"category_id"`
	BrandID     pgtype.Int8 `json:"brand_id"`
	Name        string      `json:"name"`
	Model       pgtype.Text `json:"model"`
	Sku         pgtype.Text `json:"sku"`
	Description pgtype.Text `json:"description"`
	Active      bool        `json:"active"`
}

type ProductCategory struct {
	ID               int64              `json:"id"`
	ParentCategoryID pgtype.Int8        `json:"parent_category_id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ProductOffer struct {
	ID           int64              `json:"id"`
	ProductID    int64              `json:"product_id"`
	StoreID      int64              `json:"store_id"`
	Price        pgtype.Numeric     `json:"price"`
	ListPrice    pgtype.Numeric     `json:"list_price"`
	Currency     string             `json:"currency"`
	ShippingCost pgtype.Numeric     `json:"shipping_cost"`
	ShippingFree bool               `json:"shipping_free"`
	Available    bool               `json:"available"`
	Stock        pgtype.Int4        `json:"stock"`
	Condition    string             `json:"condition"`
	ProductUrl   pgtype.Text        `json:"product_url"`
	LastUpdated  pgtype.Timestamptz `json:"last_updated"`
}

type Store struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	WebsiteUrl          pgtype.Text        `json:"website_url"`
	LogoUrl             pgtype.Text        `json:"logo_url"`
	Rating              pgtype.Numeric     `json:"rating"`
	Reputation          pgtype.Text        `json:"reputation"`
	ShippingInformation pgtype.Text        `json:"shipping_information"`
	GeneralConditions   pgtype.Text        `json:"general_conditions"`
	Active              bool               `json:"active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
