// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*)
FROM product p
WHERE p.active = TRUE
  AND ($1::bigint IS NULL OR p.category_id = $1)
  AND ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%')
`

type CountProductsParams struct {
	CategoryID pgtype.Int8 `json:"category_id"`
	Search     pgtype.Text `json:"search"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.CategoryID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id,
    p.public_id,
    p.name,
    p.model,
    p.sku,
    p.description,
    b.name AS brand_name,
    c.name AS category_name
FROM product p
LEFT JOIN brand b ON b.id = p.brand_id
LEFT JOIN product_category c ON c.id = p.category_id
WHERE p.id = $1 AND p.active = TRUE
`

type GetProductByIDRow struct {
	ID           int64       `json:"id"`
	PublicID     pgtype.UUID `json:"public_id"`
	Name         string      `json:"name"`
	Model        pgtype.Text `json:"model"`
	Sku          pgtype.Text `json:"sku"`
	Description  pgtype.Text `json:"description"`
	BrandName    pgtype.Text `json:"brand_name"`
	CategoryName pgtype.Text `json:"category_name"`
}

func (q *Queries) GetProductByID(ctx context.Context, id int64) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Model,
		&i.Sku,
		&i.Description,
		&i.BrandName,
		&i.CategoryName,
	)
	return i, err
}

const listOffersByProductID = `-- name: ListOffersByProductID :many
SELECT
    po.id,
    po.store_id,
    s.name AS store_name,
    s.logo_url AS store_logo_url,
    po.price,
    po.list_price,
    po.currency,
    po.shipping_cost,
    po.shipping_free,
    po.available,
    po.stock,
    po.condition,
    po.product_url,
    po.last_updated
FROM product_offer po
JOIN store s ON s.id = po.store_id
WHERE po.product_id = $1 AND s.active = TRUE
ORDER BY po.price ASC
`

type ListOffersByProductIDRow struct {
	ID           int64              `json:"id"`
	StoreID      int64              `json:"store_id"`
	StoreName    string             `json:"store_name"`
	StoreLogoUrl pgtype.Text        `json:"store_logo_url"`
	Price        pgtype.Numeric     `json:"price"`
	ListPrice    pgtype.Numeric     `json:"list_price"`
	Currency     string             `json:"currency"`
	ShippingCost pgtype.Numeric     `json:"shipping_cost"`
	ShippingFree bool               `json:"shipping_free"`
	Available    bool               `json:"available"`
	Stock        pgtype.Int4        `json:"stock"`
	Condition    string             `json:"condition"`
	ProductUrl   pgtype.Text        `json:"product_url"`
	LastUpdated  pgtype.Timestamptz `json:"last_updated"`
}

// Precios del mismo producto en las distintas tiendas.
func (q *Queries) ListOffersByProductID(ctx context.Context, productID int64) ([]ListOffersByProductIDRow, error) {
	rows, err := q.db.Query(ctx, listOffersByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOffersByProductIDRow
	for rows.Next() {
		var i ListOffersByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.StoreName,
			&i.StoreLogoUrl,
			&i.Price,
			&i.ListPrice,
			&i.Currency,
			&i.ShippingCost,
			&i.ShippingFree,
			&i.Available,
			&i.Stock,
			&i.Condition,
			&i.ProductUrl,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    p.id,
    p.public_id,
    p.name,
    p.model,
    p.sku,
    p.description,
    b.name AS brand_name,
    c.name AS category_name,
    MIN(po.price) FILTER (WHERE po.available)::numeric AS min_price,
    MAX(po.price) FILTER (WHERE po.available)::numeric AS max_price,
    COUNT(po.id) FILTER (WHERE po.available) AS offer_count
FROM product p
LEFT JOIN brand b ON b.id = p.brand_id
LEFT JOIN product_category c ON c.id = p.category_id
LEFT JOIN product_offer po ON po.product_id = p.id
WHERE p.active = TRUE
  AND ($3::bigint IS NULL OR p.category_id = $3)
  AND ($4::text IS NULL OR p.name ILIKE '%' || $4 || '%')
GROUP BY p.id, b.name, c.name
ORDER BY p.id
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	CategoryID pgtype.Int8 `json:"category_id"`
	Search     pgtype.Text `json:"search"`
}

type ListProductsRow struct {
	ID           int64          `json:"id"`
	PublicID     pgtype.UUID    `json:"public_id"`
	Name         string         `json:"name"`
	Model        pgtype.Text    `json:"model"`
	Sku          pgtype.Text    `json:"sku"`
	Description  pgtype.Text    `json:"description"`
	BrandName    pgtype.Text    `json:"brand_name"`
	CategoryName pgtype.Text    `json:"category_name"`
	MinPrice     pgtype.Numeric `json:"min_price"`
	MaxPrice     pgtype.Numeric `json:"max_price"`
	OfferCount   int64          `json:"offer_count"`
}

// Lista productos con paginación y precio mínimo/máximo entre tiendas.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Limit,
		arg.Offset,
		arg.CategoryID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Model,
			&i.Sku,
			&i.Description,
			&i.BrandName,
			&i.CategoryName,
			&i.MinPrice,
			&i.MaxPrice,
			&i.OfferCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
