// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	GetProductByID(ctx context.Context, id int64) (GetProductByIDRow, error)
	// Precios del mismo producto en las distintas tiendas.
	ListOffersByProductID(ctx context.Context, productID int64) ([]ListOffersByProductIDRow, error)
	// Lista productos con paginación y precio mínimo/máximo entre tiendas.
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
}

var _ Querier = (*Queries)(nil)
