apiVersion: v1
kind: Service
metadata:
  name: product-api
  labels:
    app.kubernetes.io/name: product-api
    app.kubernetes.io/component: product-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: product-api
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
