apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-test
  namespace: student-rrios
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-ceph
  resources:
    requests:
      storage: 1Gi
